[package]
name = "freetype-gen-rs"
description = "Generated unsafe bindings to FreeType 2"
license = "MIT"
version = "0.2.13"
edition = "2021"

[build-dependencies]
bindgen = "0.64.0"
cmake = "0.1"

[dependencies]
bitflags = "1.3.2"
libc = "0.2.139"
thiserror = "1.0.38"
